export const BIBLE_BOOKS = [
  { id: 'GEN', name: 'Genesis', chapters: 50, slug: 'genesis' },
  { id: 'EXO', name: 'Exodus', chapters: 40, slug: 'exodus' },
  { id: 'LEV', name: 'Leviticus', chapters: 27, slug: 'leviticus' },
  { id: 'NUM', name: 'Numbers', chapters: 36, slug: 'numbers' },
  { id: 'DEU', name: 'Deuteronomy', chapters: 34, slug: 'deuteronomy' },
  { id: 'JOS', name: 'Joshua', chapters: 24, slug: 'joshua' },
  { id: 'JDG', name: 'Judges', chapters: 21, slug: 'judges' },
  { id: 'RUT', name: 'Ruth', chapters: 4, slug: 'ruth' },
  { id: '1SA', name: '1 Samuel', chapters: 31, slug: '1-samuel' },
  { id: '2SA', name: '2 Samuel', chapters: 24, slug: '2-samuel' },
  { id: '1KI', name: '1 Kings', chapters: 22, slug: '1-kings' },
  { id: '2KI', name: '2 Kings', chapters: 25, slug: '2-kings' },
  { id: '1CH', name: '1 Chronicles', chapters: 29, slug: '1-chronicles' },
  { id: '2CH', name: '2 Chronicles', chapters: 36, slug: '2-chronicles' },
  { id: 'EZR', name: 'Ezra', chapters: 10, slug: 'ezra' },
  { id: 'NEH', name: 'Nehemiah', chapters: 13, slug: 'nehemiah' },
  { id: 'EST', name: 'Esther', chapters: 10, slug: 'esther' },
  { id: 'JOB', name: 'Job', chapters: 42, slug: 'job' },
  { id: 'PSA', name: 'Psalms', chapters: 150, slug: 'psalms' },
  { id: 'PRO', name: 'Proverbs', chapters: 31, slug: 'proverbs' },
  { id: 'ECC', name: 'Ecclesiastes', chapters: 12, slug: 'ecclesiastes' },
  { id: 'SNG', name: 'Song of Solomon', chapters: 8, slug: 'song-of-solomon' },
  { id: 'ISA', name: 'Isaiah', chapters: 66, slug: 'isaiah' },
  { id: 'JER', name: 'Jeremiah', chapters: 52, slug: 'jeremiah' },
  { id: 'LAM', name: 'Lamentations', chapters: 5, slug: 'lamentations' },
  { id: 'EZK', name: 'Ezekiel', chapters: 48, slug: 'ezekiel' },
  { id: 'DAN', name: 'Daniel', chapters: 12, slug: 'daniel' },
  { id: 'HOS', name: 'Hosea', chapters: 14, slug: 'hosea' },
  { id: 'JOL', name: 'Joel', chapters: 3, slug: 'joel' },
  { id: 'AMO', name: 'Amos', chapters: 9, slug: 'amos' },
  { id: 'OBA', name: 'Obadiah', chapters: 1, slug: 'obadiah' },
  { id: 'JON', name: 'Jonah', chapters: 4, slug: 'jonah' },
  { id: 'MIC', name: 'Micah', chapters: 7, slug: 'micah' },
  { id: 'NAH', name: 'Nahum', chapters: 3, slug: 'nahum' },
  { id: 'HAB', name: 'Habakkuk', chapters: 3, slug: 'habakkuk' },
  { id: 'ZEP', name: 'Zephaniah', chapters: 3, slug: 'zephaniah' },
  { id: 'HAG', name: 'Haggai', chapters: 2, slug: 'haggai' },
  { id: 'ZEC', name: 'Zechariah', chapters: 14, slug: 'zechariah' },
  { id: 'MAL', name: 'Malachi', chapters: 4, slug: 'malachi' },
  { id: 'MAT', name: 'Matthew', chapters: 28, slug: 'matthew' },
  { id: 'MRK', name: 'Mark', chapters: 16, slug: 'mark' },
  { id: 'LUK', name: 'Luke', chapters: 24, slug: 'luke' },
  { id: 'JHN', name: 'John', chapters: 21, slug: 'john' },
  { id: 'ACT', name: 'Acts', chapters: 28, slug: 'acts' },
  { id: 'ROM', name: 'Romans', chapters: 16, slug: 'romans' },
  { id: '1CO', name: '1 Corinthians', chapters: 16, slug: '1-corinthians' },
  { id: '2CO', name: '2 Corinthians', chapters: 13, slug: '2-corinthians' },
  { id: 'GAL', name: 'Galatians', chapters: 6, slug: 'galatians' },
  { id: 'EPH', name: 'Ephesians', chapters: 6, slug: 'ephesians' },
  { id: 'PHP', name: 'Philippians', chapters: 4, slug: 'philippians' },
  { id: 'COL', name: 'Colossians', chapters: 4, slug: 'colossians' },
  { id: '1TH', name: '1 Thessalonians', chapters: 5, slug: '1-thessalonians' },
  { id: '2TH', name: '2 Thessalonians', chapters: 3, slug: '2-thessalonians' },
  { id: '1TI', name: '1 Timothy', chapters: 6, slug: '1-timothy' },
  { id: '2TI', name: '2 Timothy', chapters: 4, slug: '2-timothy' },
  { id: 'TIT', name: 'Titus', chapters: 3, slug: 'titus' },
  { id: 'PHM', name: 'Philemon', chapters: 1, slug: 'philemon' },
  { id: 'HEB', name: 'Hebrews', chapters: 13, slug: 'hebrews' },
  { id: 'JAS', name: 'James', chapters: 5, slug: 'james' },
  { id: '1PE', name: '1 Peter', chapters: 5, slug: '1-peter' },
  { id: '2PE', name: '2 Peter', chapters: 3, slug: '2-peter' },
  { id: '1JN', name: '1 John', chapters: 5, slug: '1-john' },
  { id: '2JN', name: '2 John', chapters: 1, slug: '2-john' },
  { id: '3JN', name: '3 John', chapters: 1, slug: '3-john' },
  { id: 'JUD', name: 'Jude', chapters: 1, slug: 'jude' },
  { id: 'REV', name: 'Revelation', chapters: 22, slug: 'revelation' },
]

export function resolveBook(query) {
  if (!query) return null
  const q = query.toLowerCase().replace(/\s+/g, '-')
  return BIBLE_BOOKS.find(b => b.slug === q || b.id.toLowerCase() === q || b.name.toLowerCase() === query.toLowerCase())
}
