const SEARCH_DATA = [
  // Games
  { type: 'game', title: 'Scripture Trivia', desc: 'Test your Bible knowledge — 3 difficulty levels', icon: '❓', to: '/play/trivia', tags: ['quiz', 'trivia', 'game', 'bible', 'scripture'] },
  { type: 'game', title: 'David & Goliath', desc: 'Action game of faith', icon: '🏹', to: '/play/game/david-goliath', tags: ['david', 'goliath', 'action', 'game', 'battle'] },
  { type: 'game', title: 'Scripture Runner', desc: 'Endless runner — collect Fruits of the Spirit', icon: '🏃', to: '/play/game/runner', tags: ['runner', 'endless', 'game', 'fruits', 'spirit'] },
  { type: 'game', title: 'Parable Escape Room', desc: 'Solve riddles from the whale & lion den', icon: '🧩', to: '/play/game/escape-room', tags: ['escape', 'room', 'puzzle', 'jonah', 'daniel'] },
  { type: 'game', title: 'Spin the Verse', desc: 'Match 3 themes for a jackpot devotional', icon: '🎰', to: '/play/game/spin-the-verse', tags: ['spin', 'verse', 'match', 'casual', 'game'] },
  { type: 'game', title: 'Flashcards', desc: 'Memorize scripture with 3D flip cards', icon: '🧠', to: '/play/flashcards', tags: ['memory', 'verse', 'flashcard', 'scripture', 'memorize'] },
  { type: 'game', title: 'Activity Sheets', desc: 'Printable Bible fun for kids', icon: '🖨️', to: '/play/activity-sheets', tags: ['print', 'activity', 'sheets', 'kids', 'learning', 'download'] },
  { type: 'game', title: 'Daily Challenge', desc: 'New scramble or riddle every 24 hours', icon: '📅', to: '/play/challenge', tags: ['challenge', 'daily', 'scramble', 'riddle'] },
  // Kids Learning
  { type: 'game', title: 'Bible Alphabet', desc: 'Learn ABCs with Bible stories', icon: '🔤', to: '/kids/alphabet', tags: ['kids', 'alphabet', 'abc', 'letters', 'preschool'] },
  { type: 'game', title: 'Bible Animals', desc: 'Discover animals in the Bible', icon: '🦁', to: '/kids/animals', tags: ['kids', 'animals', 'noah', 'ark'] },
  { type: 'game', title: 'Bible Numbers', desc: 'Learn numbers with Bible', icon: '🔢', to: '/kids/numbers', tags: ['kids', 'counting', 'numbers', 'math'] },
  { type: 'game', title: 'Bible Jigsaw', desc: 'Puzzle fun with Bible scenes', icon: '🧩', to: '/kids/jigsaw', tags: ['kids', 'puzzle', 'jigsaw'] },
  { type: 'game', title: 'Word Builder', desc: 'Build words from Bible stories', icon: '📝', to: '/kids/word-builder', tags: ['kids', 'words', 'spelling', 'vocabulary'] },
  { type: 'game', title: 'Creation Coloring', desc: 'Color the days of creation', icon: '🎨', to: '/kids/coloring', tags: ['kids', 'coloring', 'art', 'creation'] },
  { type: 'game', title: 'Kids Bible Stories', desc: 'AI-narrated Bible stories for young children', icon: '📚', to: '/kids-stories', tags: ['kids', 'stories', 'bible', 'children', 'preschool'] },
  { type: 'game', title: 'Verse Scramble', desc: 'Unscramble Bible verses', icon: '🔀', to: '/kids/verse-scramble', tags: ['kids', 'verse', 'scramble', 'puzzle'] },
  // AI Tools
  { type: 'page', title: 'AI Devotional', desc: 'Personalized daily devotionals powered by AI', icon: '🙏', to: '/ai/devotional', tags: ['devotional', 'prayer', 'ai', 'faith', 'daily'] },
  { type: 'page', title: 'Bible Character Chat', desc: 'Talk to Moses, David, Paul and more', icon: '💬', to: '/ai/chat/characters', tags: ['chat', 'ai', 'characters', 'heroes', 'moses', 'david'] },
  { type: 'page', title: 'Bible Rap Generator', desc: 'AI-generated scripture raps and songs', icon: '🎵', to: '/ai/rap-generator', tags: ['rap', 'music', 'ai', 'song', 'generator', 'scripture'] },
  { type: 'page', title: 'Miracle Art Generator', desc: 'Describe a Bible scene, get AI art prompts', icon: '🖼️', to: '/ai/miracle-art', tags: ['art', 'ai', 'miracle', 'image', 'scene', 'generator'] },
  { type: 'page', title: 'My Personal Parable', desc: 'AI creates a parable just for your situation', icon: '📜', to: '/ai/personal-parable', tags: ['parable', 'ai', 'personal', 'story', 'jesus'] },
  { type: 'page', title: 'Bible Adventure Builder', desc: 'Choose a hero, answer questions, get a branching story', icon: '🗺️', to: '/ai/adventure-builder', tags: ['adventure', 'builder', 'ai', 'story', 'hero', 'david', 'esther'] },
  // Explore
  { type: 'page', title: 'Living Bible Map', desc: 'Explore Bible lands — discover locations, earn badges', icon: '🗺️', to: '/explore/world', tags: ['map', 'bible', 'jerusalem', 'israel', 'explore', 'locations', 'living'] },
  { type: 'page', title: 'Bible Explorer', desc: 'Read the Bible in 100+ translations', icon: '📖', to: '/explore/bible', tags: ['bible', 'read', 'chapter', 'verse', 'kjv', 'niv', 'translation'] },
  { type: 'page', title: 'Bible Timeline', desc: 'Journey through 6,000 years of biblical history', icon: '⏳', to: '/explore/timeline', tags: ['timeline', 'history', 'bible', 'events', 'creation', 'jesus'] },
  { type: 'page', title: 'Voice Bible Reader', desc: 'Listen to scripture with AI narration', icon: '🎙️', to: '/explore/voice-reader', tags: ['voice', 'read', 'audio', 'narration', 'scripture'] },
  { type: 'page', title: 'Original Languages', desc: 'Hebrew and Greek scripture explorer', icon: '📜', to: '/explore/language-explorer', tags: ['hebrew', 'greek', 'languages', 'original', 'bible'] },
  { type: 'page', title: 'Cross Reference', desc: 'Discover related scriptures instantly', icon: '🔗', to: '/explore/cross-reference', tags: ['cross', 'reference', 'relate', 'scripture', 'study'] },
  { type: 'page', title: 'Bible Names Explorer', desc: 'Meanings and origins of every name in Scripture', icon: '🔤', to: '/names', tags: ['names', 'bible', 'meaning', 'origin', 'hebrew'] },
  { type: 'page', title: 'Bible Family Tree', desc: 'Explore biblical genealogy', icon: '🌳', to: '/grow/family-tree', tags: ['family', 'tree', 'genealogy', 'lineage', 'biblical'] },
  // Grow
  { type: 'page', title: 'Daily Faith Habits', desc: 'Track prayer, Bible reading, gratitude and more daily', icon: '🌱', to: '/grow/habits', tags: ['habits', 'daily', 'prayer', 'reading', 'streak', 'grow'] },
  { type: 'page', title: 'Bible Certification', desc: 'Earn your Bible studies certificate', icon: '🎓', to: '/grow/certification', tags: ['certify', 'learn', 'study', 'certificate', 'bible'] },
  { type: 'page', title: 'Reading Plan', desc: 'Daily schedules to read through the Word', icon: '📅', to: '/grow/reading-plan', tags: ['plan', 'read', 'daily', 'schedule', 'bible'] },
  { type: 'page', title: 'Faith Milestones', desc: 'Track your spiritual growth and achievements', icon: '🏔️', to: '/grow/faith-milestones', tags: ['milestones', 'faith', 'growth', 'achievements', 'progress'] },
  { type: 'page', title: 'Worship Discovery', desc: 'Find worship music by mood', icon: '🎵', to: '/grow/worship', tags: ['worship', 'music', 'praise', 'songs', 'mood'] },
  // Community
  { type: 'page', title: 'Prayer Wall', desc: 'Community prayer — real-time', icon: '🌍', to: '/community/prayer', tags: ['prayer', 'community', 'pray', 'request', 'wall'] },
  { type: 'page', title: 'Leaderboard', desc: 'Top streaks, badges, and trivia champions', icon: '🏆', to: '/community/leaderboard', tags: ['leaderboard', 'streak', 'badges', 'trivia', 'ranking'] },
  { type: 'page', title: 'Chat Rooms', desc: 'Safe discussion rooms for the community', icon: '💬', to: '/community/chat', tags: ['chat', 'community', 'fellowship', 'discussion'] },
  { type: 'page', title: 'Family Groups', desc: 'Connect with church families and groups', icon: '👨‍👩‍👧‍👦', to: '/community/family', tags: ['family', 'groups', 'fellowship', 'community'] },
  { type: 'page', title: 'Prayer Beads', desc: 'Focus your heart with digital prayer beads', icon: '📿', to: '/community/prayer-beads', tags: ['prayer', 'beads', 'focus', 'meditate'] },
  { type: 'page', title: 'Prayer Partner', desc: 'Connect with a digital prayer partner', icon: '🤝', to: '/community/prayer-partner', tags: ['prayer', 'partner', 'companion', 'faith'] },
  { type: 'page', title: 'Church Finder', desc: 'Find churches near you', icon: '⛪', to: '/church-finder', tags: ['church', 'find', 'near me', 'location', 'worship'] },
  { type: 'page', title: 'Church Calendar', desc: 'Local services and community events', icon: '📅', to: '/community/events', tags: ['calendar', 'events', 'church', 'worship'] },
  // Parents
  { type: 'page', title: 'Parents and Teachers Hub', desc: 'Resources, lesson plans, and teaching tools', icon: '🏫', to: '/parents', tags: ['parents', 'teachers', 'hub', 'resources', 'lesson'] },
  { type: 'page', title: 'Printable Lesson Plans', desc: 'AI-generated lesson plans for teachers and parents', icon: '🖨️', to: '/parents/parents-teachers', tags: ['lesson', 'plan', 'printable', 'teacher', 'parent', 'download'] },
  { type: 'page', title: 'Parental Controls', desc: 'Set time limits, content filters, bedtime mode', icon: '🔒', to: '/parents/controls', tags: ['parental', 'controls', 'filter', 'time', 'limit', 'kids'] },
  // General
  { type: 'page', title: 'My Progress Dashboard', desc: 'Streak, badges, calendar', icon: '📊', to: '/dashboard', tags: ['progress', 'streak', 'badge', 'dashboard'] },
  { type: 'page', title: 'My Bookmarks', desc: 'Save and organize your favourite Bible verses', icon: '🔖', to: '/bookmarks', tags: ['bookmark', 'verse', 'save', 'favorites'] },
  { type: 'page', title: 'Go Pro', desc: 'Unlock AI tools, certification and family features', icon: '💎', to: '/premium', tags: ['pro', 'premium', 'upgrade', 'subscription'] },
  { type: 'page', title: 'Newsletter', desc: 'Free weekly printables and new game alerts', icon: '📧', to: '/newsletter', tags: ['newsletter', 'email', 'subscribe', 'printable', 'weekly'] },
  { type: 'page', title: 'Podcast', desc: 'Faith conversations for families', icon: '🎙️', to: '/podcast', tags: ['podcast', 'audio', 'listen', 'family', 'faith'] },
  { type: 'page', title: 'Spiritual Gifts Test', desc: 'Discover your unique spiritual gifts', icon: '🎁', to: '/spiritual-gifts', tags: ['spiritual', 'gifts', 'test', 'discovery', 'ministry'] },
  { type: 'page', title: 'Bible Apologetics', desc: 'Reasonable answers for your faith questions', icon: '🛡️', to: '/apologetics', tags: ['apologetics', 'defense', 'reason', 'faith', 'questions'] },
  { type: 'page', title: 'Hymn Explorer', desc: 'Discover the stories behind classic hymns', icon: '🎶', to: '/hymns', tags: ['hymns', 'music', 'worship', 'songs', 'history'] },
  { type: 'page', title: 'Church Hub', desc: 'Pastoral tools and congregation management', icon: '⛪', to: '/church/dashboard', tags: ['church', 'pastor', 'leader', 'hub', 'dashboard'] },
  { type: 'page', title: 'Prophecy Fulfillment', desc: 'See how Jesus fulfilled Old Testament prophecies', icon: '📜', to: '/prophecy', tags: ['prophecy', 'fulfillment', 'jesus', 'messiah'] },
  { type: 'page', title: 'Prayer Journal', desc: 'Write and track your personal prayers', icon: '📓', to: '/prayer-journal', tags: ['prayer', 'journal', 'write', 'personal', 'diary'] },
  { type: 'page', title: 'Daily Bible Wordle', desc: 'Five letters, six tries, one Bible word', icon: '🔠', to: '/wordle', tags: ['wordle', 'game', 'puzzle', 'word', 'daily'] },
  { type: 'page', title: 'Sermon Illustrations', desc: 'Powerful stories for your next message', icon: '💡', to: '/sermon-illustrations', tags: ['sermon', 'illustrations', 'stories', 'teaching', 'pastor'] },
  { type: 'page', title: 'Fasting Tracker', desc: 'Track your fasting journey', icon: '🕊️', to: '/fasting', tags: ['fasting', 'fast', 'spiritual', 'discipline', 'tracker'] },
  { type: 'page', title: 'Scripture Typing', desc: 'Type Bible verses to memorize them', icon: '⌨️', to: '/scripture-typing', tags: ['typing', 'scripture', 'memorize', 'practice', 'verse'] },
  { type: 'page', title: 'Couples Devotional', desc: 'Marriage-focused devotionals', icon: '💑', to: '/couples-devotional', tags: ['couples', 'marriage', 'devotional', 'relationship'] },
  { type: 'page', title: 'Sermon Writer', desc: 'AI-generated complete sermon manuscripts', icon: '✍️', to: '/sermon-writer', tags: ['sermon', 'writer', 'ai', 'preach', 'pastor'] },
  { type: 'page', title: 'Browse Everything', desc: 'Smart search across all games, tools and resources', icon: '🔍', to: '/browse', tags: ['browse', 'search', 'everything', 'all', 'filter'] },
  // Verses
  { type: 'verse', title: 'John 3:16', desc: 'For God so loved the world...', icon: '📜', to: '/play/flashcards', tags: ['john', 'love', 'god', 'world', 'salvation'] },
  { type: 'verse', title: 'Philippians 4:13', desc: 'I can do all things through Christ...', icon: '📜', to: '/play/flashcards', tags: ['philippians', 'strength', 'christ'] },
  { type: 'verse', title: 'Jeremiah 29:11', desc: 'Plans to prosper you...', icon: '📜', to: '/play/flashcards', tags: ['jeremiah', 'plans', 'hope', 'future'] },
  { type: 'verse', title: 'Psalm 23:1', desc: 'The Lord is my shepherd...', icon: '📜', to: '/play/flashcards', tags: ['psalm', 'shepherd', 'lord', 'david'] },
  { type: 'verse', title: 'Romans 8:28', desc: 'All things work for good...', icon: '📜', to: '/play/flashcards', tags: ['romans', 'good', 'love', 'purpose'] },
  { type: 'verse', title: 'Isaiah 40:31', desc: 'Those who hope in the Lord...', icon: '📜', to: '/play/flashcards', tags: ['isaiah', 'hope', 'eagle', 'strength'] },
  { type: 'verse', title: 'Proverbs 3:5-6', desc: 'Trust in the Lord...', icon: '📜', to: '/play/flashcards', tags: ['proverbs', 'trust', 'heart', 'wisdom'] },
  { type: 'verse', title: 'Joshua 1:9', desc: 'Be strong and courageous...', icon: '📜', to: '/play/flashcards', tags: ['joshua', 'strong', 'courage', 'fear'] },
];
